version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spendai-postgres
    environment:
      POSTGRES_DB: spendai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: spendai-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: 